authapp/urls.py
from django.urls import path

from . import views


app_name = "authapp"

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
]

blog/urls.py
from django.urls import path

from . import views


app_name = "blog"

urlpatterns = [
    path("", views.home, name="home"),
    path("<int:id>", views.item, name="item"),
    path("category/<int:id>", views.category, name="category"),
    path("user/<int:id>", views.user, name="user"),
    path("add_blog_item/", views.add_blog_item, name="add_blog_item"),
    path("add_category/", views.add_category, name="add_category"),
    path("test_data/", views.generate_test_data, name="test_data"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("blog/", include("blog.urls"), name="blog"),
    path("auth/", include("authapp.urls"), name="authapp"),
]

authapp/models.py
from django.db import models

# Create your models here.

authapp/forms.py
from django.forms import CharField, EmailField
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    email = EmailField(max_length=255)
    first_name = CharField(max_length=20)
    last_name = CharField(max_length=20)

    def __init__(self, *args, **kwargs) -> None:
        super(SignUpForm, self).__init__(*args, **kwargs)
        del self.fields["password2"]

    class Meta:
        model = User
        fields = [
            "username",
            "email",
            "first_name",
            "last_name",
            "password1",
        ]


class LoginForm(AuthenticationForm):
    def __init__(self, request=None, *args, **kwargs) -> None:
        super().__init__(request=request, *args, **kwargs)
        self.error_messages["invalid_login"] = "Username or password is invalid"

authapp/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as auth_login, logout as auth_logout
from django.contrib.auth.decorators import login_required

from authapp.forms import SignUpForm, LoginForm


def signup(request):
    form = SignUpForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            form.save()
            return redirect("authapp:login")

    return render(request, "authapp/signup.j2", context={"form": form})


def login(request):
    form = LoginForm(data=(request.POST or None))
    if request.method == "POST":
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect("blog:home")

    return render(request, "authapp/login.j2", context={"form": form})


@login_required(login_url="authapp:login")
def logout(request):
    auth_logout(request)
    return redirect("authapp:login")

authapp/templates/authapp/login.j2
{% extends "base.j2" %}
{% load static %}

{% block title %}Log In{% endblock title %}

{% block main %}
<h1 class="main-header">Log In</h1>
<div class="form-container" id="form-container">
   <form class="form" id="form" action="{% url 'authapp:login' %}" method="POST">
      <div class="form__wrap">
         {% csrf_token %}
         {% for field in form %}
            <div class="form__field">
               <label class="form__label" for="{{ field.id_for_label }}">
                  {{ field.label }}
               </label>
               {{ field }}
               {{ field.errors }}
            </div>
         {% endfor %}
         {% for error in form.non_field_errors %}
            <div class="danger form__danger">
               {{ error }}
            </div>
         {% endfor %}
      </div>
      <input class="btn form__btn" type="submit" value="Login">
   </form>
</div>
<p style="text-align: center; margin-top: 20px;">
   Go to
   <a style="text-decoration: underline;" href="{% url 'authapp:signup' %}">
      signup page
   </a>
</p>
<script src="{% static 'js/form.js' %}"></script>
{% endblock main %}

authapp/templates/authapp/signup.j2
{% extends "base.j2" %}
{% load static %}

{% block title %}Sign Up{% endblock title %}

{% block main %}
<h1 class="main-header">Sign Up</h1>
<div class="form-container" id="form-container">
   <form class="form" id="form" action="{% url 'authapp:signup' %}" method="POST">
      <div class="form__wrap">
         {% csrf_token %}
         {% for field in form %}
            <div class="form__field">
               <label class="form__label" for="{{ field.id_for_label }}">
                  {{ field.label }}
                  {% if field.field.required %}*{% endif %}
               </label>
               {{ field }} 
               {{ field.errors }}
            </div>
         {% endfor %}
      </div>
      <input class="btn form__btn" type="submit" value="Register">
   </form>
</div>
<p style="text-align: center; margin-top: 20px;">
        Go to
   <a style="text-decoration: underline;" href="{% url 'authapp:login' %}">
      login page
   </a>
</p>
<script src="{% static 'js/form.js' %}"></script>
{% endblock main %}